### ISSUE TITLE
Not working on Note 3

### ISSUE THREAD

**Issue by llcool** [ultramancool/AudioPrivacy#14]
The app doesn't hide album art on my Note 3. Tried the both Google and Samsung players.

**Comment by ultramancool** [comment]
Confirmed - missing some kind of hook on Google Play Music background setting. It's working on many other apps (Spotify, Pocket Casts, DI.fm) so I'll have to see what they're doing differently.

**Comment by ultramancool** [comment]
Latest version should resolve this.
