### ISSUE TITLE
Not working on Sony Xperia Z5 Lollipop 5.1.1

### ISSUE THREAD

**Issue by JollyRocker** [ultramancool/AudioPrivacy#15]
Found this forum as it's really annoying having album artwork on lock screen, even when playing Spotify or SONOS at home.
Dumbfounded that there's still no stock toggle to choose whether to show it or not.
But even though this app was recommended, it doesn't work for me.

**Comment by ultramancool** [comment]
Sorry, can't reproduce as I don't have a Sony device - spotify works for me on CM at least. Be aware that we can only block background album art though - you must block the notification for your media player yourself via Android settings. 

If someone with one wants to look into this I'll take PR.
