### ISSUE TITLE
audio privacy does not work for my phone

### ISSUE THREAD

**Issue by peterpanes** [ultramancool/AudioPrivacy#6]
Samsung SGH I747 with AT&T stock 4.4.2 Android OS
Non of the functions work on my phone:, beyondpod, pandora and others show the supersized audio label when locked. Can you please advice? In options I have selected both options.

**Comment by ultramancool** [comment]
I can't offer support for specific ROMs, even if they're stock when they've been messed with by a manufacturer, sorry.
