### ISSUE TITLE
Feature-Request: Completely disable lockscreen music controls

### ISSUE THREAD

**Issue by WeaponsLeft** [ultramancool/AudioPrivacy#7]
Hello,

PLEASE add a feature to completely hide/disable/remove all lockscreen music controls/buttons !

I really hate this lockscreen crap it always has a delay when switching music,
makes screen ugly and in my case it is completely useles because I use
"QuickAccess"-XPosedModule to access my music when the screen is locked.

I searched the web and couldn't find a way to remove this shit...

Thank you :)

**Comment by ultramancool** [comment]
Lock screen music controls are no longer present in 5.1, I suggest you upgrade if you haven't already.
