### ISSUE TITLE
How can I have it NOT hide my owner details?

### ISSUE THREAD

**Issue by cjfm** [ultramancool/AudioPrivacy#9]
I installed this on my Note II and yep, it hides the ugly, pixellated, mis-sized album art that KitKat smeared over my lock screen. All good.

But it also removes user info that scrolled on my lock screen showing another number to ring if I lost the phone and someone found it. Can I not have that if I use this module? Because that bit of the system (I think it is part of Android, as all the phones of various brands and operating systems in this house can do it) was useful!

**Comment by ultramancool** [comment]
I can't offer support for specific ROMs, even if they're stock when they've been messed with by a manufacturer, sorry.
